### PR TITLE
init

### PR DESCRIPTION
**Pull request by Macy6**
**(Required) Please make sure your github profile has an email we can contact you by**
_Your email is the best way for us to contact you regarding the status of your submission!_

tags: student, coop winter 2021

### CODE REVIEW

**Comment by omasabdullah** [comment]
@Macy6 let us know which labels you want us to add and we will do that for you :)

**Comment by Macy6** [comment]
> @Macy6 let us know which labels you want us to add and we will do that for you :)

Thanks! "Coop" and "Student" labels would be sufficient for me!

**Comment by omasabdullah** [comment]
@Macy6 which coop specifically were you looking for? The fall or winter?

**Comment by Macy6** [comment]
> @Macy6 which coop specifically were you looking for? The fall or winter?

Winter 2021 term :)

**Pull request closed without merging**
