### PR TITLE
Update solution_python.py

### PR DESCRIPTION
**Pull request by AIeasy**
**(Required) Please make sure your github profile has an email we can contact you by**
_Your email is the best way for us to contact you regarding the status of your submission!_

### CODE REVIEW

**Comment by AIeasy** [comment]
@omasabdullah here is my pull request

**Comment by AIeasy** [comment]
#73

**Comment by AIeasy** [comment]
#73 @omasabdullah

**Comment by omasabdullah** [comment]
@AIeasy it looks like theres an implementation issue with some of your functions that is causing the tests to fail

**Comment by AIeasy** [comment]
Coop fall 2020 ,Student

**Pull request closed without merging**
